import { Orbitron, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const orbitron = Orbitron({
    subsets: ['latin'],
    weight: ["400", "500", "600", "700", "800", "900"],
    variable: '--font-orbitron-sans',
});

const geistMono = Geist_Mono({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-geist-mono',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${orbitron.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
